// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelDiscovery(arg1) {
  return window['go']['main']['App']['CancelModelDiscovery'](arg1);
}

export function CheckEnvVar(arg1) {
  return window['go']['main']['App']['CheckEnvVar'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ContinueSession(arg1) {
  return window['go']['main']['App']['ContinueSession'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function DeleteGlobalSkill(arg1) {
  return window['go']['main']['App']['DeleteGlobalSkill'](arg1);
}

export function DeleteModels(arg1, arg2) {
  return window['go']['main']['App']['DeleteModels'](arg1, arg2);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function ExecuteLaunchOMP(arg1, arg2) {
  return window['go']['main']['App']['ExecuteLaunchOMP'](arg1, arg2);
}

export function FetchModels(arg1, arg2) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetModelsDeleteImpact(arg1, arg2) {
  return window['go']['main']['App']['GetModelsDeleteImpact'](arg1, arg2);
}

export function GetProviderDeleteImpact(arg1) {
  return window['go']['main']['App']['GetProviderDeleteImpact'](arg1);
}

export function ImportDiscoveredModels(arg1, arg2) {
  return window['go']['main']['App']['ImportDiscoveredModels'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function LaunchOMP(arg1, arg2) {
  return window['go']['main']['App']['LaunchOMP'](arg1, arg2);
}

export function ListGlobalSkills() {
  return window['go']['main']['App']['ListGlobalSkills']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function MarkUpdateChecked() {
  return window['go']['main']['App']['MarkUpdateChecked']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function SaveModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveModel'](arg1, arg2, arg3);
}

export function SetSelectedModel(arg1, arg2) {
  return window['go']['main']['App']['SetSelectedModel'](arg1, arg2);
}

export function SetSelectedProvider(arg1) {
  return window['go']['main']['App']['SetSelectedProvider'](arg1);
}

export function TestModel(arg1, arg2) {
  return window['go']['main']['App']['TestModel'](arg1, arg2);
}

export function UpdateModelRoles(arg1) {
  return window['go']['main']['App']['UpdateModelRoles'](arg1);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
