// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {updater} from '../models';
import {provider} from '../models';
import {main} from '../models';
import {skills} from '../models';
import {config} from '../models';
import {sessions} from '../models';
import {omp} from '../models';

export function CancelModelDiscovery(arg1:string):Promise<void>;

export function CheckEnvVar(arg1:string):Promise<system.EnvCheckResult>;

export function CheckForUpdate():Promise<updater.CheckResult>;

export function ContinueSession(arg1:string):Promise<void>;

export function CreateProvider(arg1:provider.SaveInput):Promise<main.ProviderMutationResult>;

export function DeleteGlobalSkill(arg1:string):Promise<skills.Inventory>;

export function DeleteModels(arg1:string,arg2:Array<string>):Promise<config.AppState>;

export function DeleteProvider(arg1:string):Promise<config.AppState>;

export function DeleteSession(arg1:string):Promise<Array<sessions.Info>>;

export function ExecuteLaunchOMP(arg1:string,arg2:string):Promise<void>;

export function FetchModels(arg1:string,arg2:string):Promise<provider.DiscoveryResult>;

export function GetAppState():Promise<config.AppState>;

export function GetModelsDeleteImpact(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function GetProviderDeleteImpact(arg1:string):Promise<Array<string>>;

export function ImportDiscoveredModels(arg1:string,arg2:Array<provider.ModelInfo>):Promise<config.AppState>;

export function InstallUpdate():Promise<void>;

export function LaunchOMP(arg1:string,arg2:string):Promise<omp.LaunchPreview>;

export function ListGlobalSkills():Promise<skills.Inventory>;

export function ListProviders():Promise<Array<provider.View>>;

export function ListSessions():Promise<Array<sessions.Info>>;

export function ListWSLDistros():Promise<Array<main.WSLDistro>>;

export function MarkUpdateChecked():Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function ResolveNativePaths():Promise<main.PathDetectResult>;

export function ResolveWSLPaths(arg1:string):Promise<main.PathDetectResult>;

export function SaveModel(arg1:string,arg2:string,arg3:provider.ModelInfo):Promise<config.AppState>;

export function SetSelectedModel(arg1:string,arg2:string):Promise<config.AppState>;

export function SetSelectedProvider(arg1:string):Promise<config.AppState>;

export function TestModel(arg1:string,arg2:string):Promise<provider.ConnectionTestResult>;

export function UpdateModelRoles(arg1:Array<config.RoleUpdate>):Promise<config.AppState>;

export function UpdateProvider(arg1:string,arg2:provider.SaveInput):Promise<main.ProviderMutationResult>;

export function UpdateSettings(arg1:config.AppSettings):Promise<config.AppState>;
